
import P1c from "../assets/Work_Images/P1 C.png";
import P2c from "../assets/Work_Images/P2 C.webp";
import P3c from "../assets/Work_Images/P3 C.png";
import P4c from "../assets/Work_Images/P4 C.jpg";
import P5c from "../assets/Work_Images/P5 C.png";
import P6c from "../assets/Work_Images/P6 C.png";
import P7c from "../assets/Work_Images/P7 C.png";
import P8c from "../assets/Work_Images/P8 C.jpg";

// import P9c from "../assets/Work_Images/P9 C.png"

import P10c from "../assets/Work_Images/P10 C.png";
import P11c from "../assets/Work_Images/P11 C.jpg";
// import P11c from "../assets/Work_Images/P11 C.png"
import P12c from "../assets/Work_Images/P12 C.png";
// import P13c from "../assets/Work_Images/P13 C.png"
import P14c from "../assets/Work_Images/P14 C.png";



export const tovoDetails = [

  {id:0,
    location: " Creek Harbour, Dubai, UAE [EMAAR]",
    typology: "Commercial",
    status: "on-going",
    year: 2023,
    buildArea:"13,800 Sq.ft",
    siteArea:"17,500 Sq.ft",
    scope: "Architecture / Facade",
    clickable: true,
    team: "Mithun Adhitya, Karthik Keshev",
    images: [P1c],
  },
  {id: 1,
  location: "OMR, Chennai, Tamil Nadu, India",
  typology: "Commercial",
  status: "Completed",
  year: 2023,
  buildArea:"13,800 Sq.ft",
  siteArea: "17,500 Sq.ft",
  scope: "Architecture / Facade",
  clickable: true,
  team: "Mithun Adhitya, Karthik Keshev",
  images: [P1c],
} ,
  {id: 2,
  location: "Banjara Hills, Hyderabad, India",
  typology: "Residence",
  status: "Completed",
  year: 2023,
  buildArea:"6,000 Sq.ft",
  siteArea: "3,600 Sq.ft",
  scope: "Interior / Facade",
  clickable: true,
  team: "Karthik Keshev, Mithun Adhitya, Benny Samuel",
  images:[P2c],
},
  {id: 3,
  location: "Porur, Chennai, Tamil Nadu, India",
  typology: "Commercial",
  status: "Completed",
  year: 2023,
  buildArea: "34,600 Sq.ft",
  siteArea: "24,600 Sq.ft",
  scope: "Architecture / Facade",
  clickable: true,
  team: "Dinesh Kumar, Mithun Adhitya",
  images: [P3c],
},
  {id: 4,
  location: "Coimbatore, Tamil Nadu, India",
  typology: "Retail",
  status: "Completed",
  year: 2023,
  buildArea: "900 Sq.ft",
  siteArea: "1,200 Sq.ft",
  scope: "Architecture / Facade",
  clickable: true,
  team: "Mithun Adhitya, Karthik Keshev",
  images: [P4c],
},
  {id: 5,
  location: "Puducherry, India",
  typology: "Residence",
  status: "Completed",
  year: 2023,
  buildArea: "6,000 Sq.ft",
  siteArea: "3,600 Sq.ft",
  scope: "Interior / Facade",
  clickable: true,
  team: "Karthik Keshev, Mithun Adhitya, Benny Samuel",
  images:[P5c],
},
  {id: 6,
  location: "Indira Nagar, Bengaluru, India",
  typology: "Commercial",
  status: "Completed",
  year: 2023,
  buildArea: "34,600 Sq.ft",
  siteArea: "24,600 Sq.ft",
  scope: "Architecture / Facade",
  clickable: true,
  team: "Dinesh Kumar, Mithun Adhitya",
  images: [P6c],
},
  {id: 7,
  location: "Chennai, Tamil Nadu, India [Phoenix Marketcity]",
  typology: "Retail",
  status: "Completed",
  year: 2024,
  buildArea: "900 Sq.ft",
  siteArea: "1,200 Sq.ft",
  scope: "Architecture / Facade",
  clickable: true,
  team: "Mithun Adhitya, Karthik Keshev",
  images: [P7c],
},
  {id: 8,
  location: "Trichy, Tamil Nadu, India",
  typology: "Residence",
  status: "Completed",
  year: 2024,
  buildArea: "6,000 Sq.ft",
  siteArea: "3,600 Sq.ft",
  scope: "Interior / Facade",
  clickable: true,
  team: "Karthik Keshev, Mithun Adhitya, Benny Samuel",
  images:[P8c],
},
  {id: 9,
  location: "Himayat Nagar, Hyderabad, India",
  typology: "Commercial",
  status: "Completed",
  year: 2024,
  buildArea: "34,600 Sq.ft",
  siteArea: "24,600 Sq.ft",
  scope: "Architecture / Facade",
  clickable: true,
  team: "Dinesh Kumar, Mithun Adhitya",
  images: [P10c],
},
  {id: 10,
  location: "Koramangala, Bengaluru, India [Mantri Mall]",
  typology: "Retail",
  status: "Completed",
  year: 2024,
  buildArea: "900 Sq.ft",
  siteArea: "1.200 Sq.ft",
  scope: "Architecture / Facade",
  clickable: true,
  team: "Mithun Adhitya, Karthik Keshev",
  images: [P11c],
},
  {id: 11,
  location: "Church Street, Bengaluru, India",
  typology: "Residence",
  status: "on-going",
  year: 2025,
  buildArea: "6,000 Sq.ft",
  siteArea: "3,600 Sq.ft",
  scope: "Interior / Facade",
  clickable: true,
  team: "Karthik Keshev, Mithun Adhitya, Benny Samuel",
  images:[P12c],
},
  {id: 12,
  location: "Whitefield, Bengaluru, India",
  typology: "Commercial",
  status: "on-going",
  year: 2025,
  buildArea: "34,600 Sq.ft",
  siteArea: "24,600 Sq.ft",
  scope: "Architecture / Facade",
  clickable: true,
  team: "Dinesh Kumar, Mithun Adhitya",
  images: [P12c],
},
  {id: 13,
  location: "Colaba, Mumbai, India",
  typology: "Retail",
  status: "on-going",
  year: 2025,
  buildArea: "900 Sq.ft",
  siteArea: "1,200 Sq.ft",
  scope: "Architecture / Facade",
  clickable: true,
  team: "Mithun Adhitya, Karthik Keshev",
  images: [P12c],
},
  {id: 14,
  location: "DLF CyberHub, Gurgaon, India",
  typology: "Residence",
  status: "on-going",
  year: 2025,
  buildArea: "6,000 Sq.ft",
  siteArea: "3,600 Sq.ft",
  scope: "Interior / Facade",
  clickable: true,
  team: "Karthik Keshev, Mithun Adhitya, Benny Samuel",
  images:[P12c],
},

]